import "@/assets/css/styles.scss";
import { Barlow_Condensed } from 'next/font/google';
import { Header, Footer } from '@/components/'

const barlow = Barlow_Condensed({ subsets: ['latin'], weight: ['100', '400', '900'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
