import "@/assets/css/styles.scss";
import "@fortawesome/fontawesome-svg-core/styles.css"; 

import { Header, Footer, Search } from '@/components/'
import { config } from "@fortawesome/fontawesome-svg-core";
import SearchBig from "@/components/Search/SearchBig";
config.autoAddCss = false; 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
        <SearchBig />
      </body>
    </html>
  )
}
